export COLOSSAL_CAVE_API_KEY=YOUR SECRET HERE
export COLOSSAL_CAVE_API_SECRET=YOUR SECRET HERE
export COLOSSAL_CAVE_ACCESS_TOKEN=YOUR SECRET HERE
export COLOSSAL_CAVE_ACCESS_TOKEN_SECRET=YOUR SECRET HERE
export COLOSSAL_CAVE_DATABASE="advent.sqlite"
